name: Build assets on ubuntu

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack & pnpm 10
        run: |
          corepack enable
          corepack prepare pnpm@10.0.0 --activate
          pnpm --version

      - name: Install JS deps (pnpm)
        run: pnpm install --frozen-lockfile

      - name: Install Ruby deps (bundler)
        run: bundle install --without development test

      - name: Precompile assets
        env:
          RAILS_ENV: production
          RAILS_SERVE_STATIC_FILES: 'true'
          RAILS_LOG_TO_STDOUT: '1'
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          bundle exec rails assets:clobber
          bundle exec rails assets:precompile

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: |
            public/vite
            public/assets
            public/packs
