name: Build assets

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "1"
      NODE_OPTIONS: "--max-old-space-size=4096"
      BUNDLE_WITHOUT: "development:test"
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5'
          bundler-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Enable corepack
        run: |
          npm i -g corepack
          corepack enable

      - name: Install JS deps
        run: |
          yarn install --immutable || yarn install --frozen-lockfile

      - name: Precompile Rails assets
        run: |
          bundle exec rails assets:clobber
          bundle exec rails assets:precompile

      - name: Pack build artifacts
        run: |
          tar -C public -czf public/build-assets.tgz vite assets packs 2>/dev/null || true
          ls -lah public/build-assets.tgz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-assets
          path: public/build-assets.tgz
          if-no-files-found: error
