# .github/workflows/ci.yml
name: build-compose

jobs:
  build:
    runs-on: ubuntu-latest          # на этом раннере docker уже есть
    services:                       # включаем DinD-демон
      docker:
        image: docker:25.0-dind
        options: --privileged       # нужен для DinD
        env:
          DOCKER_TLS_CERTDIR: ""    # отключаем TLS внутри dind
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: tcp://localhost:2375   # чтобы клиент говорил с демоном в сервисе

    steps:
      - uses: actions/checkout@v4

      # ставим compose-plugin (v2) — это и есть новая «docker compose»
      - name: Install docker-cli + compose plugin
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli docker-compose-plugin
          docker compose version            # проверяем

      - name: Build & run containers
        run: |
          docker compose down --remove-orphans || true
          docker compose up --build -d
